bump_version: null
lint: null
nf_core_version: 3.0.2
org_path: null
repository_type: pipeline
template:
  author: Danilo Di Leo, Emelie Nilsson and Daniel Lundin
  description: nf-core/magmap is a bioinformatics best-practice analysis pipeline
    for mapping reads to a (large) collections of genomes.
  force: false
  is_nfcore: true
  name: magmap
  org: nf-core
  outdir: .
  skip_features: null
  version: 1.0.0
update: null
